url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

sass:
  load_paths:
    - ./vendor/bundle/ruby/3.1.0/gems/bootstrap-5.3.1/assets/stylesheets
